import type { Metadata } from "next";

import "./globals.css";

import "./globals.css";
import Footer from "@/components/Homepage/Footer/Footer";
import Navbar from "@/components/Homepage/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
