import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css";
import Navbar from "./components/Homepage/Navbar/Navbar";
=======

import "./globals.css";

import "./globals.css";
import Navbar from "./components/Homepage/Navbar/Navbar";
import Footer from "@/components/common/HomePage/Footer/Footer";
>>>>>>> origin/master

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
